config/routes.rb
Rails.application.routes.draw do
  resources :boards, only: [:index, :show]

  post '/create_board', to: 'boards#create', as: :create_board

  root 'boards#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/board.rb
class Board < ApplicationRecord
  validates :email, presence: true, length: { maximum: 50 }, format: { with: URI::MailTo::EMAIL_REGEXP }
  validates :rows, :cols, presence: true, numericality: { only_integer: true }
  validates :mines, presence: true

  scope :last_ten_records, -> { order(created_at: :desc).limit(10) }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  rescue_from ActiveRecord::RecordNotFound, with: :base_render_record_not_found
  rescue_from ActiveRecord::RecordInvalid, with: :base_render_unprocessable_entity
  rescue_from ActiveRecord::RecordNotUnique, with: :base_render_record_not_unique

  private

  def base_render_record_not_found
    flash[:alert] = "Record Not Found"
    redirect_to root_path
  end

  def base_render_unprocessable_entity(exception)
    flash[:alert] = exception.message
    redirect_back_or_to '/', status: :unprocessable_entity
  end

  def base_render_record_not_unique
    flash[:alert] = "Record Not Unique"
    redirect_back_or_to '/', status: :forbidden
  end
end

app/controllers/boards_controller.rb
class BoardsController < ApplicationController

  before_action :find_board, only: :show
  before_action :create_valid_board, only: :create

  def index
    @recent_boards = Board.last_ten_records
    @boards = Board.all
  end

  def create
    if @board.save!
      redirect_to @board
    else
      flash[:alert] = "Board creation failed."
      render :index
    end
  end

  def show
    @mines_board = BoardCreator.generate_board(@board.mines, @board.rows, @board.cols) if @board
  end

  private

  def board_params
    params.require(:board).permit(:email, :rows, :cols, :mines)
  end

  def create_valid_board
    @rows, @cols, @mines = board_params.values_at(:rows, :cols, :mines).map(&:to_i)

    if @mines > @rows * @cols
      flash[:alert] = "Mines can't be greater than the total number of cells."
      redirect_back_or_to '/', status: :unprocessable_entity
    end

    mines_location = BoardCreator.place_mines(@rows, @cols, @mines)
    @board = Board.new(email: board_params[:email], rows: @rows, cols: @cols, mines: mines_location)
  end

  def find_board
    @board = Board.find_by(id: params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/boards_helper.rb
module BoardsHelper
    def show_button(value)
        bg = 'background'+ value.to_s
        content_tag(:button, "", class: "button #{bg} border")
    end
end
  
  
  
  
  
  

app/views/boards/_board_form.html.erb
<%= form_with(model: Board, url: create_board_path, method: :post, local: true) do |form| %>
  <div class="mb-3 mt-3">
    <%= form.email_field :email, class: 'form-control', placeholder: 'Email', required: true %>
  </div>

  <div class="mb-3">
    <%= form.number_field :rows, class: 'form-control', placeholder: 'Rows', required: true, min: 1 %>
  </div>

  <div class="mb-3">
    <%= form.number_field :cols, class: 'form-control', placeholder: 'Columns', required: true, min: 1 %>
  </div>

  <div class="mb-3">
    <%= form.number_field :mines, class: 'form-control', placeholder: 'Mines', required: true, min: 1 %>
  </div>

  <%= form.submit "Generate Board", class: 'btn btn-primary mt-3' %>
<% end %>

app/views/boards/_boards_table.html.erb
<table class="table table-bordered table-hover">
    <thead class="table-dark">
    <tr>
        <th scope="col">#</th>
        <th scope="col">Email</th>
        <th scope="col">Rows</th>
        <th scope="col">Cols</th>
        <th scope="col">Mines</th>
        <th scope="col">Board</th>
    </tr>
    </thead>
    <tbody>
    <% boards.each_with_index do |board, index| %>
      <tr>
        <th scope="row"><%= index + 1 %></th>
        <td><%= board.email %></td>
        <td><%= board.rows %></td>
        <td><%= board.cols %></td>
        <td><%= board.mines.count %></td>
        <td><%= link_to "Show", board, class: 'btn btn-primary' %></td>
      </tr>
    <% end %>
    </tbody>
</table>

app/views/boards/index.html.erb
<% if flash[:alert] %>
  <div class="alert alert-danger">
    <%= flash[:alert] %>
  </div>
<% end %>

<div class="grid-container">
  <div class="item board-creator">
    <div class="card-heading bg-primary text-white text-center rounded p-1">
      <h2>Board Info</h2>
    </div>
    <%= render 'boards/board_form' %>
  </div>

  <div class="item recent-boards">
    <h2 class="card-heading bg-primary text-white text-center rounded p-1 mb-4">Recent Boards</h2>
    <div class="table-responsive" style="max-height: 400px; overflow-y: auto;">
      <%= render partial: 'boards/boards_table', locals: { boards: @recent_boards } %>
    </div>
  </div>

  <div class="item all-boards">
    <h2 class="card-heading bg-primary text-white text-center rounded p-1 text-center mb-4">All Boards</h2>
    <div class="table-responsive" style="max-height: 500px; overflow-y: auto;">
      <%= render partial: 'boards/boards_table', locals: { boards: @boards } %>
    </div>
  </div>
</div>

app/views/boards/show.html.erb
<div class="container mt-5">
  <div class="card shadow p-5 my-4">
    <h2 class="mb-4">Board Details</h2>
    <div class="table-responsive">
      <table class="table table-bordered table-striped">
        <tbody>
          <tr>
            <th scope="row">Email</th>
            <td><%= @board.email %></td>
          </tr>
          <tr>
            <th scope="row">No. of Columns</th>
            <td><%= @board.cols %></td>
          </tr>
          <tr>
            <th scope="row">No. of Rows</th>
            <td><%= @board.rows %></td>
          </tr>
          <tr>
            <th scope="row">No. of Mines</th>
            <td><%= @board.mines.count %></td>
          </tr>
        </tbody>
      </table>
    </div>
  </div>
  
  <div class="card rounded">
      <div class="card-body p-0">
        <h2 class="card-title mb-4 font-weight-bold text-center bg-primary text-white py-2 rounded">Minesweeper Board</h2>
      </div>
      <div class="overflow-auto" style="max-height: 500px;">
        <div class="d-flex flex-column align-items-center">
          <% @board.rows.times do |r| %>
            <div class="inline">
              <% @board.cols.times do |c| %>
                <%= show_button(@mines_board[r][c]) %>
              <% end %>
            </div>
          <% end %>
        </div>
      </div>
  </div>

  <div class="mt-4">
    <%= link_to 'Back', boards_path, class: 'btn btn-primary' %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Minesweeper</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>